/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSensitiveRouteImport } from './routes/api/sensitive'
import { Route as ApiStepUpCompleteRouteImport } from './routes/api/step-up/complete'
import { Route as ApiWebhooksAuthdogRouteImport } from './routes/api/webhooks/authdog'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSensitiveRoute = ApiSensitiveRouteImport.update({
  id: '/api/sensitive',
  path: '/api/sensitive',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStepUpCompleteRoute = ApiStepUpCompleteRouteImport.update({
  id: '/api/step-up/complete',
  path: '/api/step-up/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksAuthdogRoute = ApiWebhooksAuthdogRouteImport.update({
  id: '/api/webhooks/authdog',
  path: '/api/webhooks/authdog',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/sensitive': typeof ApiSensitiveRoute
  '/api/step-up/complete': typeof ApiStepUpCompleteRoute
  '/api/webhooks/authdog': typeof ApiWebhooksAuthdogRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/sensitive': typeof ApiSensitiveRoute
  '/api/step-up/complete': typeof ApiStepUpCompleteRoute
  '/api/webhooks/authdog': typeof ApiWebhooksAuthdogRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/sensitive': typeof ApiSensitiveRoute
  '/api/step-up/complete': typeof ApiStepUpCompleteRoute
  '/api/webhooks/authdog': typeof ApiWebhooksAuthdogRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/api/sensitive' | '/api/step-up/complete' | '/api/webhooks/authdog'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/sensitive' | '/api/step-up/complete' | '/api/webhooks/authdog'
  id:
    | '__root__'
    | '/'
    | '/api/sensitive'
    | '/api/step-up/complete'
    | '/api/webhooks/authdog'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiSensitiveRoute: typeof ApiSensitiveRoute
  ApiStepUpCompleteRoute: typeof ApiStepUpCompleteRoute
  ApiWebhooksAuthdogRoute: typeof ApiWebhooksAuthdogRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sensitive': {
      id: '/api/sensitive'
      path: '/api/sensitive'
      fullPath: '/api/sensitive'
      preLoaderRoute: typeof ApiSensitiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/step-up/complete': {
      id: '/api/step-up/complete'
      path: '/api/step-up/complete'
      fullPath: '/api/step-up/complete'
      preLoaderRoute: typeof ApiStepUpCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/authdog': {
      id: '/api/webhooks/authdog'
      path: '/api/webhooks/authdog'
      fullPath: '/api/webhooks/authdog'
      preLoaderRoute: typeof ApiWebhooksAuthdogRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiSensitiveRoute: ApiSensitiveRoute,
  ApiStepUpCompleteRoute: ApiStepUpCompleteRoute,
  ApiWebhooksAuthdogRoute: ApiWebhooksAuthdogRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
